services:
  immich-sync:
    build: .
    container_name: immich-sync
    environment:
      - TZ=UTC
      # - IMMICH_API_KEY=your-key # If not using config.json
      # - IMMICH_API_URL=http://immich-server/api # If not using config.json
      # - IMMICH_READD_TRASHED_ITEMS=true # If not using config.json, set to true to re-upload trashed items
    volumes:
      - ./config.json:/app/config.json # Mount the config file (create it with your settings)
    restart: unless-stopped
